# export PATH="$PATH:$HOME/.rvm/bin" -> to thwart rvm's install.sh
# $HOME/.rvm/scripts/rvm -> to thwart rvm's install.sh
# nvm.sh -> to thwart nvm's install.sh
[[ -s "$HOME/.bashrc" ]] && source "$HOME/.bashrc" # Load the default .bashrc
