#!/usr/bin/env zsh

export NVM_DIR="$HOME/.nvm"

# Find the correct nvm init script
if [[ -s "/usr/local/opt/nvm/nvm.sh" ]]; then
  # Installed via homebrew
  export NVM_INIT_SCRIPT_DIR="/usr/local/opt/nvm"

elif [[ -s "$NVM_DIR/nvm.sh" ]]; then
  # Installed via https://github.com/creationix/nvm
  export NVM_INIT_SCRIPT_DIR="$NVM_DIR"
fi

# This loads nvm"
zdot load "$NVM_INIT_SCRIPT_DIR/nvm.sh"

# Autoload add-zsh-hook
autoload -U add-zsh-hook

# Call `nvm use` automatically in a directory with a .nvmrc file.
# @see  https://github.com/creationix/nvm#zsh
__loadnvmrc() {
  local node_version=$(nvm version)
  local node_default=$(nvm version default)
  local nvmrc_path="$(nvm_find_nvmrc)"

  if [ -n "$nvmrc_path" ]; then
    local nvmrc_node_version=$(nvm version "$(cat "${nvmrc_path}")")
    if [ "$nvmrc_node_version" = "N/A" ]; then
      nvm install &> /dev/null
    elif [ "$nvmrc_node_version" != "$node_version" ]; then
      nvm use --delete-prefix $nvmrc_node_version &> /dev/null
    fi
  elif [ $node_version != $node_default ]; then
    nvm use --delete-prefix $node_default &> /dev/null
  fi

  export node_path="$(nvm which $(nvm version))"
}

# Add method to zsh hook for `chpwd` commands
add-zsh-hook chpwd __loadnvmrc
__loadnvmrc
