#!/usr/bin/env zsh
#
# Define environment variables for login, non-login, interactive and
# non-interactive shells.
#
# Authors:
#   Larry Gordon
#
# Execution Order
#   https://github.com/psyrendust/alf/templates/home
#
# License:
#   The MIT License (MIT) <http://psyrendust.mit-license.org/2014/license.html>
# ------------------------------------------------------------------------------
# [[ -s "$HOME/.profile" ]] && source "$HOME/.profile"

# Load up nvm
# nvm.sh -> to thwart nvm's install.sh
[[ -s "$NVM_DIR/nvm.sh" ]] && source "$NVM_DIR/nvm.sh"


# ------------------------------------------------------------------------------
# Initialize zplug
# ------------------------------------------------------------------------------
if [[ ! -d ~/.zplug ]]; then
  git clone https://github.com/zplug/zplug ~/.zplug
  source ~/.zplug/init.zsh && zplug update --self
else
  source ~/.zplug/init.zsh
fi


# ------------------------------------------------------------------------------
# oh-my-zsh init
# ------------------------------------------------------------------------------
# add a function path
fpath=($ZSH/functions $ZSH/completions $fpath)

# Load all stock functions (from $fpath files) called below.
autoload -U compaudit compinit

: ${ZSH_DISABLE_COMPFIX:=true}

# Set ZSH_CUSTOM to the path where your custom config files
# and plugins exists, or else we will use the default custom/
if [[ -z "$ZSH_CUSTOM" ]]; then
    ZSH_CUSTOM="$ZSH/custom"
fi

# Set ZSH_CACHE_DIR to the path where cache files should be created
# or else we will use the default cache/
if [[ -z "$ZSH_CACHE_DIR" ]]; then
  ZSH_CACHE_DIR="$ZSH/cache"
fi


# Load all of the config files in ~/.oh-my-zsh/lib that end in .zsh
# TIP: Add files you don't want in git to .gitignore
# zplug "robbyrussell/oh-my-zsh", use:"bzr.zsh"
# zplug "robbyrussell/oh-my-zsh", use:"clipboard.zsh"
# zplug "robbyrussell/oh-my-zsh", use:"diagnostics.zsh"
# zplug "robbyrussell/oh-my-zsh", use:"lib/*.zsh"
# don't use lib/git.zsh, messes up output of `git branch`
# zplug "robbyrussell/oh-my-zsh", use:"lib/git.zsh"
# zplug "robbyrussell/oh-my-zsh", use:"prompt_info_functions.zsh"
zplug "robbyrussell/oh-my-zsh", use:"lib/compfix.zsh"
zplug "robbyrussell/oh-my-zsh", use:"lib/completion.zsh"
zplug "robbyrussell/oh-my-zsh", use:"lib/correction.zsh"
zplug "robbyrussell/oh-my-zsh", use:"lib/directories.zsh"
zplug "robbyrussell/oh-my-zsh", use:"lib/functions.zsh"
zplug "robbyrussell/oh-my-zsh", use:"lib/grep.zsh"
zplug "robbyrussell/oh-my-zsh", use:"lib/history.zsh"
zplug "robbyrussell/oh-my-zsh", use:"lib/key-bindings.zsh"
zplug "robbyrussell/oh-my-zsh", use:"lib/misc.zsh"
zplug "robbyrussell/oh-my-zsh", use:"lib/nvm.zsh"
zplug "robbyrussell/oh-my-zsh", use:"lib/spectrum.zsh"
zplug "robbyrussell/oh-my-zsh", use:"lib/termsupport.zsh"
zplug "robbyrussell/oh-my-zsh", use:"lib/theme-and-appearance.zsh"


# ------------------------------------------------------------------------------
# om-my-zsh plugins
# ------------------------------------------------------------------------------
zplug "plugins/apache2", from:oh-my-zsh, defer:1
zplug "plugins/colored-man-pages", from:oh-my-zsh, defer:1
zplug "plugins/command-not-found", from:oh-my-zsh, defer:1
zplug "plugins/colorize", from:oh-my-zsh, defer:1
zplug "plugins/copydir", from:oh-my-zsh, defer:1
zplug "plugins/copyfile", from:oh-my-zsh, defer:1
zplug "plugins/cp", from:oh-my-zsh, defer:1
zplug "plugins/docker", from:oh-my-zsh, defer:1
zplug "plugins/encode64", from:oh-my-zsh, defer:1
zplug "plugins/extract", from:oh-my-zsh, defer:1
zplug "plugins/fasd", from:oh-my-zsh, defer:1
zplug "plugins/git", from:oh-my-zsh, defer:1
zplug "plugins/gitfast", from:oh-my-zsh, defer:1
zplug "plugins/node", from:oh-my-zsh, defer:1
zplug "plugins/npm", from:oh-my-zsh, defer:1
zplug "plugins/nvm", from:oh-my-zsh, defer:1
zplug "plugins/osx", from:oh-my-zsh, defer:1
zplug "plugins/systemadmin", from:oh-my-zsh, defer:1
zplug "plugins/urltools", from:oh-my-zsh, defer:1
zplug "plugins/yarn", from:oh-my-zsh, defer:1


# ------------------------------------------------------------------------------
# dotfiles plugins
# ------------------------------------------------------------------------------
zplug "$ZSH_CUSTOM/plugins/aliases", from:local, defer:2
zplug "$ZSH_CUSTOM/plugins/git", from:local, defer:2


# ------------------------------------------------------------------------------
# zsh plugins
# ------------------------------------------------------------------------------
zplug "zsh-users/zsh-completions", defer:0
zplug "zsh-users/zsh-syntax-highlighting", defer:0
zplug "zsh-users/zsh-history-substring-search", defer:3


# ------------------------------------------------------------------------------
# My theme
# ------------------------------------------------------------------------------
zplug mafredri/zsh-async, from:github, defer:2
zplug sindresorhus/pure, use:pure.zsh, from:github, as:theme, defer:3


# ------------------------------------------------------------------------------
# Install plugins if there are plugins that have not been installed
# ------------------------------------------------------------------------------
if ! zplug check --verbose; then
  printf "Install? [y/N]: "
  if read -q; then
    echo; zplug install
  fi
fi

# ------------------------------------------------------------------------------
# Then, source packages and add commands to $PATH
# ------------------------------------------------------------------------------
# # debug mode
# zplug clean && zplug clear
# zplug load --verbose
alias zplug_refresh="zplug clean && zplug clear && zplug load --verbose"

zplug load
